version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker  # Replace with your own password
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes  # Use only for development, set a password for production
    ports:
      - '6379:6379'
    volumes:
      - polls_redis_data:/bitnami/redis/data

volumes:
  polls_pg_data:
  polls_redis_data: